### ISSUE TITLE
RangeError: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by mkozjak** [qaap/jsonresponse#1]
When
```
{
	"first_name": "Mary",
	"id": "4c694598-3d83-4fbf-ba0a-f0cc854d54ab-xxxxxx",
	"is_default": true,
	"language_id": "719ad246-6ae2-47e6-8a37-f31401deaebc-xxxxxx",
	"last_name": "Rosenberg",
	"main_pin": "0000",
	"name": "Mary",
	"parental_pin": "0000",
	"parental_rating": 12,
	"password": "0000",
	"refresh_token": "",
	"skin_id": "c34bf7d7-b713-4e70-bc36-7f820833747b-xxxxxx",
	"status": "active",
	"subscriber_id": "f35e029d-99af-4022-a6d8-2149c93a8b5f-xxxxxx",
	"type": "standard",
	"uid": "scr01_usr1"
}
```
is given as a 2nd parameter to the function we get:

```RangeError: Maximum call stack size exceeded
    at convertToClient (/opt/dev/github.com/qaap/crowd/node_modules/jsonresponse2/lib/index.js:49:25)
    at convertToClient (/opt/dev/github.com/qaap/crowd/node_modules/jsonresponse2/lib/index.js:69:33)
    at convertToClient (/opt/dev/github.com/qaap/crowd/node_modules/jsonresponse2/lib/index.js:69:33)
    at convertToClient (/opt/dev/github.com/qaap/crowd/node_modules/jsonresponse2/lib/index.js:69:33)
    at convertToClient (/opt/dev/github.com/qaap/crowd/node_modules/jsonresponse2/lib/index.js:69:33)
    at convertToClient (/opt/dev/github.com/qaap/crowd/node_modules/jsonresponse2/lib/index.js:69:33)
    at convertToClient (/opt/dev/github.com/qaap/crowd/node_modules/jsonresponse2/lib/index.js:69:33)
    at convertToClient (/opt/dev/github.com/qaap/crowd/node_modules/jsonresponse2/lib/index.js:69:33)
    at convertToClient (/opt/dev/github.com/qaap/crowd/node_modules/jsonresponse2/lib/index.js:69:33)
    at convertToClient (/opt/dev/github.com/qaap/crowd/node_modules/jsonresponse2/lib/index.js:69:33)
    at convertToClient (/opt/dev/github.com/qaap/crowd/node_modules/jsonresponse2/lib/index.js:69:33)
    at convertToClient (/opt/dev/github.com/qaap/crowd/node_modules/jsonresponse2/lib/index.js:69:33)
    at convertToClient (/opt/dev/github.com/qaap/crowd/node_modules/jsonresponse2/lib/index.js:69:33)
    at convertToClient (/opt/dev/github.com/qaap/crowd/node_modules/jsonresponse2/lib/index.js:69:33)
    at convertToClient (/opt/dev/github.com/qaap/crowd/node_modules/jsonresponse2/lib/index.js:69:33)
    at convertToClient (/opt/dev/github.com/qaap/crowd/node_modules/jsonresponse2/lib/index.js:69:33)
    at convertToClient (/opt/dev/github.com/qaap/crowd/node_modules/jsonresponse2/lib/index.js:69:33)
    at convertToClient (/opt/dev/github.com/qaap/crowd/node_modules/jsonresponse2/lib/index.js:69:33)
    at convertToClient (/opt/dev/github.com/qaap/crowd/node_modules/jsonresponse2/lib/index.js:69:33)
    at convertToClient (/opt/dev/github.com/qaap/crowd/node_modules/jsonresponse2/lib/index.js:69:33)
    at convertToClient (/opt/dev/github.com/qaap/crowd/node_modules/jsonresponse2/lib/index.js:69:33)
    at convertToClient (/opt/dev/github.com/qaap/crowd/node_modules/jsonresponse2/lib/index.js:69:33)```

**Comment by mkozjak** [comment]
Was a false example. '[Object object]' was feeded to the library in one project.
